name: 'Close stale issues'
on:
  schedule:
    - cron: '0 1,13 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          only-labels: 'needs-more-info'
          days-before-issue-stale: 2
          stale-issue-message: 'This issue is stale because it has been open 2 days with no activity. Remove stale label or comment or this will be closed in 1 days.'
          days-before-issue-close: 1
          close-issue-message: 'This issue was closed because it has been stalled for 1 days with no activity.'
